name: Node Ci workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    defaults:
      run:
        working-directory: ./animals

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./animals/package-lock.json
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test --passWithNoTests
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: ./animals
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#      - name: SonarQube Quality Gate check
#        uses: sonarsource/sonarqube-quality-gate-action@master
#        with:
#          scanMetadataReportFile: ./animals/.scannerwork/report-task.txt
#        # Force to fail step after specific time
#        timeout-minutes: 5
#        env:
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

